on join:
	set metadata tag "health" of player to 100
	set metadata tag "mana" of player to 100
	while player is online:
		scrollPartyScore(player, (metadata tag "partyShift" of player))
		set {_maxHP} to hpStat(player)
		set {_maxMP} to mpStat(player)
		set {_hpRegen} to HPRegenStat(player)
		set {_mpRegen} to MPRegenStat(player)
		loop 5 times:
			send action bar "&c[Health: %metadata tag ""health"" of player%&4/&c%{_maxHP}% ❤]     &b[Mana: %metadata tag ""mana"" of player%&3/&b%{_maxMP}% ♤]" to player
			wait 1 second
		if metadata tag "interruptActionBar" of player is not set:
			set metadata "health" of player to (metadata "health" of player)+{_hpRegen}
			set metadata "mana" of player to (metadata "mana" of player)+{_mpRegen}
			if metadata "health" of player > {_maxHP}:
				set metadata tag "health" of player to hpStat(player)
			if metadata "mana" of player > {_maxMP}:
				set metadata tag "mana" of player to mpStat(player)
			send action bar "&c[Health: %metadata tag ""health"" of player%&4/&c%{_maxHP}% ❤]     &b[Mana: %metadata tag ""mana"" of player%&3/&b%{_maxMP}% ♤]" to player
		else:
			wait 1 second
			clear metadata tag "interruptActionBar" of player

every 10 minutes:
	send "&6[Broadcast] &eSaved all inventories of level 5+" to all players where [input's level > 5]
	execute console command "updateranks"
	loop all players:
		profileInv(loop-player,"save")
